language: java

addons:
  sonarcloud:
    organization: "sbaltes-github"
    token: $de.uni-trier.st.fst18.yobinx

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar 
